-- Seed EducationLevel
IF NOT EXISTS (SELECT 1 FROM EducationLevel WHERE Code = 'DIPLOMA')
BEGIN
    INSERT INTO EducationLevel (Code) VALUES ('DIPLOMA'), ('ASSOCIATE'), ('BACHELOR'), ('MASTER'), ('PROFESSIONAL_DOCTORATE'), ('PHD'), ('SEMINARY');
END
GO

-- Seed FieldOfStudy
IF NOT EXISTS (SELECT 1 FROM FieldOfStudy WHERE Code = 'ACCOUNTING')
BEGIN
    INSERT INTO FieldOfStudy (Code) VALUES ('ACCOUNTING'),('BUSINESS_MANAGEMENT'),('FINANCIAL_MANAGEMENT'),('ECONOMICS'),('LAW'),('COMPUTER_ENGINEERING'),('INDUSTRIAL_ENGINEERING'),('ELECTRICAL_ENGINEERING'),('CIVIL_ENGINEERING'),('MECHANICAL_ENGINEERING'),('MATHEMATICS'),('PHYSICS'),('CHEMISTRY'),('BIOLOGY'),('MEDICINE'),('NURSING'),('PHARMACY'),('LITERATURE'),('POLITICAL_SCIENCE'),('SOCIOLOGY'),('PSYCHOLOGY'),('OTHER');
END
GO
